### ISSUE TITLE
feat: sleepmode for uffizzi clusters

### ISSUE THREAD

**Issue by waveywaves** [UffizziCloud/uffizzi_cli#332] opened 2023-09-11 22:17 UTC
### Use CLI to put clusters to sleep manually

```
$ uffizzi cluster sleep cluster-1
```
sets the below spec on the said cluster. Triggering it to sleep. 
```yaml
spec:
  sleep: true
```

### Use CLI to wake the clusters up

```
$ uffizzi cluster wake cluster-1
```
sets the below spec on the said cluster. Triggering it to sleep. 
```yaml
spec:
  sleep: false
```

**Comment by moklidia** [comment] 2023-10-02 08:19
Duplicate of https://github.com/UffizziCloud/uffizzi_cli/issues/339

**Closed by moklidia** 2023-10-02 08:19 UTC
Labels: community-new
